import { NavLink } from "react-router";
import { useAuth } from "../store/authStore";
import { TypeAnimation } from "react-type-animation";
import {
  pageWrapper,
  pageTitleClass,
  bodyText,
  primaryBtn,
  secondaryBtn,
  subHeadingClass,
  mutedText,
} from "../styles/common";

function Home() {
  const isAuthenticated = useAuth((state) => state.isAuthenticated);

  return (
    <div className="bg-[#f4f1ee] min-h-screen">
      {/* HERO */}
      <div className="bg-gradient-to-br from-[#1a1a2e] via-[#16213e] to-[#0f3460] py-28 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-[0.7rem] font-bold uppercase tracking-[0.25em] text-[#a89cf7] mb-5">
            AI-Powered Resume Analysis
          </p>
          <TypeAnimation
            sequence={[
              "Get Your Resume ATS-Ready",
              1200,
              "",
              50,
            ]}
            wrapper="h1"
            className="text-5xl md:text-6xl font-bold text-white tracking-tight leading-tight mb-6"
            cursor={false}
            repeat={Infinity}
          />
          <p className="text-[#b0aac0] text-lg leading-relaxed max-w-2xl mx-auto mb-10">
            Upload your resume, choose your target role, and get an instant ATS
            score, missing skills, recruiter feedback, and AI-powered
            recommendations.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            {isAuthenticated ? (
              <NavLink
                to="/profile/upload"
                className="bg-[#6c63ff] text-white font-semibold px-8 py-3.5 rounded-xl hover:bg-[#5548e0] hover:shadow-xl hover:shadow-[#6c63ff]/30 transition-all duration-200 text-sm"
              >
                Upload Resume
              </NavLink>
            ) : (
              <>
                <NavLink
                  to="/register"
                  className="bg-[#6c63ff] text-white font-semibold px-8 py-3.5 rounded-xl hover:bg-[#5548e0] hover:shadow-xl hover:shadow-[#6c63ff]/30 transition-all duration-200 text-sm"
                >
                  Get Started
                </NavLink>
                <NavLink
                  to="/login"
                  className="border border-white/20 text-white/90 font-medium px-8 py-3.5 rounded-xl hover:bg-white/10 transition-all duration-200 text-sm"
                >
                  Sign In
                </NavLink>
              </>
            )}
          </div>
        </div>
      </div>

      {/* FEATURES */}
      <div className="border-t border-[#e8e3dc]">
        <div className={pageWrapper}>
          <p className="text-center text-[0.65rem] font-bold uppercase tracking-[0.25em] text-[#6c63ff] mb-3">
            What we offer
          </p>
          <h2 className={`${subHeadingClass} text-center text-[#1a1a2e] text-2xl mb-10`}>
            Everything you need to land the job
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5">
            {[
              {
                title: "ATS Score",
                desc: "Instantly calculate your resume's compatibility score with ATS systems used by real recruiters.",
                accent: "#6c63ff",
              },
              {
                title: "Missing Skills",
                desc: "Know exactly which skills are missing for your target role — Frontend, Backend, Full Stack, or Data Analyst.",
                accent: "#2ecc8a",
              },
              {
                title: "AI Recommendations",
                desc: "Receive 5 personalized, actionable tips generated by GPT-4 or Gemini to improve your resume.",
                accent: "#f0894d",
              },
              {
                title: "Recruiter Feedback",
                desc: "Read simulated recruiter feedback to understand how hiring managers view your resume.",
                accent: "#6c63ff",
              },
              {
                title: "Weakness Detection",
                desc: "Identify weak action verbs, poor formatting, and missing achievements instantly.",
                accent: "#e05252",
              },
              {
                title: "Score Prediction",
                desc: "See your predicted improved ATS score after applying all recommendations.",
                accent: "#2ecc8a",
              },
            ].map((feature) => (
              <div
                key={feature.title}
                className="bg-white border border-[#e8e3dc] rounded-2xl p-7 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300 group"
              >
                <div
                  className="w-2 h-2 rounded-full mb-4"
                  style={{ backgroundColor: feature.accent }}
                />
                <p className="text-base font-semibold text-[#1a1a2e] mb-2">
                  {feature.title}
                </p>
                <p className="text-sm text-[#9e9aa7] leading-relaxed">
                  {feature.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ROLES */}
      <div className="border-t border-[#e8e3dc] bg-white">
        <div className={pageWrapper}>
          <p className="text-center text-[0.65rem] font-bold uppercase tracking-[0.25em] text-[#6c63ff] mb-3">
            Supported Roles
          </p>
          <h2 className={`${subHeadingClass} text-center text-[#1a1a2e] text-2xl mb-10`}>
            Analyze for your target role
          </h2>
          <div className="flex flex-wrap justify-center gap-3">
            {[
              "Frontend Developer",
              "Backend Developer",
              "Full Stack Developer",
              "Data Analyst",
            ].map((role) => (
              <span
                key={role}
                className="bg-[#f4f1ff] border border-[#d4cff7] text-[#5548e0] text-sm font-semibold px-6 py-2.5 rounded-full"
              >
                {role}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;
